name: "First workflow"

on: push 

jobs: 
  first job: 
      runs on: ubuntu-latest
      steps: 
      - name: Welcome Message 
        run: echo "Hi Sohail, Welcome to Github actions!"

      - name: List files 
        run: ls -al 
